### ISSUE TITLE
About the main change between pytorch 0.3.1 and 1.0？

### ISSUE THREAD

**Issue by BangguWu** [MandyMo/DARTS#3]
I'm very interested in your code, because I don't know much about the main update history and differences between pytorch 0.3.1 and 1.0, so I would like to know what are the main modified code, Thanks

**Comment by MandyMo** [comment]
I found the offical code didn't work well with pytorch 1.0 or later, then I rewrite some of the code by myself.

Therefore, I don't care about the difference between the offical version and this repo.

**Comment by BangguWu** [comment]
Thanks for your reply.
